### ISSUE TITLE
Trouble running the test

### ISSUE THREAD

**Issue by davidgrenier** [theburningmonk/SimpleSpeedTester#7]
Hi,

I wanted to add FsPickler and then send a pull request, but when I cloned the repo I noticed two problems.

1- It seems the FAKE nuget (if any) didn't get downloaded while all other nuget came through fine.
2- The solution references fastJSON project which doesn't seem to be present, I noticed there seemed to be a fastJSON nuget in there with higher version # but not sure if the old one could be removed.

Thanks!

**Comment by theburningmonk** [comment]
The FAKE nuget package is installed only when you run the build.cmd script, that seems to be the way a lot of other projects are set up (I based on the FSharp.ProjectScaffold).

As for the reference to fastJSON are you working off the master branch? The develop branch is more up to date, I haven't updated master since there hasn't been any change to the test harness itself. It's a bit late over here but I can have a look at the fastJson reference tomorrow to see if there's something wrong there.

**Comment by davidgrenier** [comment]
Thanks mate, will have a second look!

**Comment by davidgrenier** [comment]
Ok seems I managed to run build and it installed fake+ongoing.

Still see the following though:
C:\Projects\SimpleSpeedTester\lib\fastJSON v1.9.6\fastJSON\fastJSON.csproj
: error  : The project file could not be loaded. Could not find a part of
the path 'C:\Projects\SimpleSpeedTester\lib\fastJSON
v1.9.6\fastJSON\fastJSON.csproj'.
 C:\Projects\SimpleSpeedTester\lib\fastJSON v1.9.6\fastJSON\fastJSON.csproj

But it doesn't look to be a showstopper, perhaps I can just remove that
dependency?
